 name: CI
 on: [push, pull_request]
 jobs:
  MainCI:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install_system
        run: |
          sudo apt update
          sudo apt install python
          sudo pip install -r data_collector/requirements.txt
